<?php

class sitePages
{
    static function get($index=FALSE)
    {
        $levels = appConfig::getSetting('accessLevels');

        $pages = [

            'access' => [

                'updateImports'                         => $levels['developer'],
                'pagesTester'                           => $levels['developer'],
                'clearTestDBJson'                       => $levels['developer'],
                'updateRequestIDJson'                   => $levels['developer'],
                'updateSeriesIDJson'                    => $levels['developer'],
                'switchIgnoreFieldJson'                 => $levels['developer'],
                'changeTestRecordModeJson'              => $levels['developer'],
                'changeTestModeJson'                    => $levels['developer'],
                'listTester'                            => $levels['developer'],
                'searchTester'                          => $levels['developer'],
                'testNewTalliesInventory'               => $levels['developer'],
                'importOldTalliesInventory'             => $levels['developer'],
                'inventoryImports'                      => $levels['developer'],
                'optimizationMigrationInventory'        => $levels['developer'],
                'runDatabaseCheck'                      => $levels['developer'],
                'importPalletSheetsInventory'           => $levels['developer'],
                'inventoryImports'                      => $levels['developer'],
                'containerReportsAppCrons'              => $levels['developer'],
                'rushOrdersNoticesAppCrons'             => $levels['developer'],
                'emailProcessedLadingAppCrons'          => $levels['developer'],
                'emailShippedLadingAppCrons'            => $levels['developer'],
                'emailInvalidPickTicketAppCrons'        => $levels['developer'],
                'emailInvoiceNotificationsAppCrons'     => $levels['developer'],
                'emailTransferMezzanineAppCrons'        => $levels['developer'],
                'shippedOrderDailyReportAppCrons'       => $levels['developer'],
                'searchCronsTasks'                      => $levels['developer'],
                'modifyUpdatesList'                     => $levels['developer'],
                'searchMinMaxRanges'                    => $levels['developer'],
                'submitMinMaxRangeAppJSON'              => $levels['developer'],
                'updateMinMaxRangeAppJSON'              => $levels['developer'],
                'printViewInvoices'                     => $levels['developer'],
                'updateInvoiceMonthAppJSON'             => $levels['developer'],
                'runDBCheckJson'                        => $levels['developer'],
                'runDBUpdateJson'                       => $levels['developer'],
                'dbCommandsIframeDevelopers'            => $levels['developer'],
                'dbCheckerDevelopers'                   => $levels['developer'],
                'updateTesterListJson'                  => $levels['developer'],
                'toggleTesterSessionJson'               => $levels['developer'],
                'getTestingInfoJson'                    => $levels['developer'],
                'addTestJson'                           => $levels['developer'],
                'removeTestJson'                        => $levels['developer'],
                'generateReceiving'                     => $levels['developer'],
                'addClientNotesAppJSON'                 => $levels['developer'],
                'addOrderClientNotesAppJSON'            => $levels['developer'],
                'invoiceSummaryAppCrons'                => $levels['developer'],
                'cartonLogSummaryAppCrons'              => $levels['developer'],
                'palletLogSummaryAppCrons'              => $levels['developer'],
                'outboundOrdersSummaryAppCrons'         => $levels['developer'],
                'styleHistorySummaryAppCrons'           => $levels['developer'],
                'lastCartonLogsAppCrons'                => $levels['developer'],
                'agingLACartonSummaryAppCrons'          => $levels['developer'],
                'agingNJCartonSummaryAppCrons'          => $levels['developer'],
                'agingTOCartonSummaryAppCrons'          => $levels['developer'],
                'agingFACartonSummaryAppCrons'          => $levels['developer'],
                'agingLAOrderSummaryAppCrons'           => $levels['developer'],
                'agingNJOrderSummaryAppCrons'           => $levels['developer'],
                'agingTOOrderSummaryAppCrons'           => $levels['developer'],
                'agingFAOrderSummaryAppCrons'           => $levels['developer'],
                'agingBillingSummaryAppCrons'           => $levels['developer'],
                'invoiceReceivingSummaryAppCrons'       => $levels['developer'],
                'invoiceOrderProcessingSummaryAppCrons' => $levels['developer'],
                'invoiceStorageSummaryAppCrons'         => $levels['developer'],
                'invoiceStorageUpdateCartonAppCrons'    => $levels['developer'],
                'testMailAppCrons'                      => $levels['developer'],
                'emailReceivingWeeklyReportAppCrons'    => $levels['developer'],
                'dailyReceivingContainerReportAppCrons' => $levels['developer'],

                // Pages you need owner level to view
                'test'                                  => $levels['owner'],
                'databasePanel'                         => $levels['owner'],
                'searchUsers'                           => $levels['owner'],
                'resetPasswordUsers'                    => $levels['owner'],
                'resetPasswordAppJSON'                  => $levels['owner'],

                // Pages you need admin level to view
                'sccInventory'                          => $levels['admin'],
                'sccGetAppJSON'                         => $levels['admin'],
                'sccUpdateAppJSON'                      => $levels['admin'],
                'updateShippedOrders'                   => $levels['admin'],
                'getTablesAppJSON'                      => $levels['admin'],
                'updateShippedCartonsAppJSON'           => $levels['admin'],
                'createTallyInventory'                  => $levels['admin'],
                'recordTallySheetsReceiving'            => $levels['admin'],
                'addUsers'                              => $levels['admin'],
                'editUsers'                             => $levels['admin'],
                'employeeJson'                          => $levels['admin'],
                'employeesJson'                         => $levels['admin'],
                'dtEditableJson'                        => $levels['user'],
                'dtEditableAddJson'                     => $levels['admin'],
                'autocompleteJson'                      => $levels['admin'],
                'adminHistory'                          => $levels['admin'],
                'consolidationScanners'                 => $levels['admin'],
                'displayConsolidation'                  => $levels['admin'],
                'waveLocations'                         => $levels['admin'],
                'splitAllInventory'                     => $levels['admin'],
                'searchUsersLevel'                      => $levels['admin'],
                'getContainerNamesAppJSON'              => $levels['admin'],
                'getProductInfoAppJSON'                 => $levels['admin'],
                'createOrderPickTicketAppJSON'          => $levels['admin'],
                'getLocationNamesAppJSON'               => $levels['admin'],
                'getContainerTallyAppJSON'              => $levels['admin'],
                'updateTallyAppJSON'                    => $levels['admin'],
                'getContainerInfoAppJSON'               => $levels['admin'],
                'recordSheetsPlates'                    => $levels['admin'],
                'seldatUPCAppJSON'                      => $levels['admin'],
                'checkSeldatUPCAppJSON'                 => $levels['admin'],
                'splitBatchesInventory'                 => $levels['admin'],
                'addPalletSheetsAppJson'                => $levels['admin'],
                'searchPlates'                          => $levels['admin'],
                'displayLabelPlates'                    => $levels['admin'],
                'displayUPCWavePicks'                   => $levels['admin'],
                'splitCartonAppJSON'                    => $levels['admin'],
                'recorTallySheetsReceiving'             => $levels['admin'],
                'recorTallySheetsReceiving'             => $levels['admin'],
                'updateRCLogPrintAppJSON'               => $levels['admin'],
                'updateRCLabelAppJSON'                  => $levels['admin'],
                'readyToCompleteAppJSON'                => $levels['admin'],
                'labelReceiving'                        => $levels['admin'],
                'completeRCLogAppJSON'                  => $levels['admin'],
                'checkRCLogLocationsAppJSON'            => $levels['admin'],
                'updateInvoiceProcessingAppJSON'        => $levels['admin'],
                'getClientCostsAppJSON'                 => $levels['admin'],
                'waveOneConsolidation'                  => $levels['admin'],
                'clientConsolidateAppJSON'              => $levels['admin'],
                'getUPCMovementsAppJSON'                => $levels['admin'],
                'consolidationMoveAppJSON'              => $levels['admin'],
                'addCartonsToBatchAppJSON'              => $levels['admin'],
                'updateBatchDimensionAppJSON'           => $levels['admin'],
                'adjustScanners'                        => $levels['admin'],
                'createPlatesAppJSON'                   => $levels['admin'],
                'createRCLabelsAppJSON'                 => $levels['admin'],
                'createUCCLabelsAppJSON'                => $levels['admin'],
                'getAdjustInventoryAppJSON'             => $levels['admin'],
                'adjustInventoryAppJSON'                => $levels['admin'],
                'getShippingFromAppJSON'                => $levels['admin'],
                'createBarcodeAppJSON'                  => $levels['admin'],
                'displayScanNumberOrders'               => $levels['admin'],
                'listWavePicks'                         => $levels['admin'],
                'importTransfers'                       => $levels['admin'],
                'listTransfers'                         => $levels['admin'],
                'displayTransfers'                      => $levels['admin'],
                'searchInactiveInventoryScanners'       => $levels['admin'],
                'inactiveInventoryScanners'             => $levels['admin'],
                'automatedScannerAppJSON'               => $levels['admin'],
                'editDirectoriesOnlineOrders'           => $levels['admin'],
                'searchClientEmails'                    => $levels['admin'],
                'zeroOutInventoryScanners'              => $levels['admin'],
                'shippedOrdersScanners'                 => $levels['admin'],
                'editUpcs'                              => $levels['admin'],
                'updateUpcInfoAppJSON'                  => $levels['admin'],
                'editCategoriesUpcs'                    => $levels['admin'],
                'checkScanContainerCellAppJSON'         => $levels['admin'],
                'checkImportContainerCellAppJSON'       => $levels['admin'],
                'emailMinMaxMezzanineInfoAppCrons'      => $levels['admin'],
                'transferMezzanineOnlineOrderAppCrons'  => $levels['admin'],
                'searchMinMax'                          => $levels['admin'],
                'submitMinMaxAppJSON'                   => $levels['admin'],
                'updateMinMaxAppJSON'                   => $levels['admin'],
                'updateClientMinMaxAppJSON'             => $levels['admin'],
                'addNewUPCsSeldatOriginal'              => $levels['admin'],
                'adminSearchLocations'                  => $levels['admin'],
                'printViewInvoices'                     => $levels['admin'],
                'updateInvoiceMonthAppJSON'             => $levels['admin'],
                'transferMezzanineScanners'             => $levels['admin'],
                'displayBOLabelBillOfLadings'           => $levels['admin'],
                'generateManualBOLAppJSON'              => $levels['admin'],
                'updateCustomerInfoAppJSON'             => $levels['admin'],
                'insertCustomerInfoAppJSON'             => $levels['admin'],
                'updateCustContactInfoAppJSON'          => $levels['admin'],
                'searchCustContactInfoAppJSON'          => $levels['admin'],
                'deleteCustContactsAppJSON'             => $levels['admin'],
                'getCustomerInfoAppJSON'                => $levels['admin'],
                'getLaborAppJSON'                       => $levels['admin'],
                'updateLaborAppJSON'                    => $levels['admin'],
                'getChargeCodesAppJSON'                 => $levels['admin'],
                'updateClientCostsAppJSON'              => $levels['admin'],
                'deleteClientCostsAppJSON'              => $levels['admin'],
                'invoiceDataAppJSON'                    => $levels['admin'],
                'updateInvoTablesAppJSON'               => $levels['admin'],
                'chargeCodeMasterInvoices'              => $levels['admin'],
                'createCycleCountAppJSON'               => $levels['admin'],
                'acceptCountItemsAppJSON'               => $levels['admin'],
                'recountCountItemsAppJSON'              => $levels['admin'],
                'deleteCycleCountAppJSON'               => $levels['admin'],
                'detailsInvoices'                       => $levels['admin'],
                'ordersOutbound'                        => $levels['admin'],
                'actualReceiving'                       => $levels['admin'],
                'inspectionReportReceiving'             => $levels['admin'],
                'containerReportReceiving'              => $levels['admin'],
                'checkVolumeRatesAppJSON'               => $levels['admin'],
                'downloadCartonHistoryScanners'         => $levels['admin'],
                'mezzanineTransferredInventory'         => $levels['admin'],
                'printMultiLicenseScanners'             => $levels['admin'],
                'changeCartonStatusScanners'            => $levels['admin'],
                'changeStatusInventory'                 => $levels['admin'],


                // Pages you need user level to view
                'listUsers'                             => $levels['user'],
                'mailerJson'                            => $levels['user'],
                'insertOrderBatchAppJSON'               => $levels['user'],

                'pickCartonsInventory'                  => $levels['user'],
                'pickErrorsInventory'                   => $levels['user'],
                'availableInventory'                    => $levels['user'],
                'componentsLogs'                        => $levels['user'],
                'listAdjustments'                       => $levels['user'],

                'orderCheckInScanners'                  => $levels['user'],
                'defaultMain'                           => $levels['user'],
                'menuMain'                              => $levels['user'],
                'mobileMenuMain'                        => $levels['user'],
                'userHistory'                           => $levels['user'],
                'plateLocationScanners'                 => $levels['user'],
                'locationsScanners'                     => $levels['user'],
                'listAddPlates'                         => $levels['user'],
                'datatablesJson'                        => $levels['user'],
                'addPlatesAppJSON'                      => $levels['user'],
                'displayPlates'                         => $levels['user'],
                'ShippingCheckinScanners'               => $levels['user'],
                'onlineOrderCheckOutAppJSON'            => $levels['user'],
                'orderLabelLocationScanners'            => $levels['user'],
                'checkInOutWorkOrders'                  => $levels['user'],
                'listAddOrderLabels'                    => $levels['user'],
                'printOrderLabels'                      => $levels['user'],
                'addOrderLabelsAppJSON'                 => $levels['user'],
                'displayOrderLabels'                    => $levels['user'],
                'displayWorkOrderLabels'                => $levels['user'],
                'printUCCOrderLabels'                   => $levels['user'],
                'importOnlineOrders'                    => $levels['user'],
                'packingListAdmin'                      => $levels['user'],
                'getPackingListAdmin'                   => $levels['user'],
                'printPackingListAdmin'                 => $levels['user'],
                'listInvoices'                          => $levels['user'],
                'processInvoices'                       => $levels['user'],
                'profileVendors'                        => $levels['user'],
                'platesAdmin'                           => $levels['user'],
                'neworderAdmin'                         => $levels['user'],
                'getMultiRowOrdersAppJSON'              => $levels['user'],
                'pickingAppJSON'                        => $levels['user'],
                'orderProcessingCheckOutAppJSON'        => $levels['user'],
                'displayBarcodes'                       => $levels['user'],
                'listExportedOnlineOrders'              => $levels['user'],
                'printLabelOnlineOrders'                => $levels['user'],
                'importCarrierOnlineOrders'             => $levels['user'],
                'filterSearcherJson'                    => $levels['user'],
                'searchOnlineOrders'                    => $levels['user'],
                'addContainers'                         => $levels['user'],
                'receivingToStockScanners'              => $levels['user'],
                'shipOnGunScanners'                     => $levels['user'],
                'getContainerInfoForRCAppJSON'          => $levels['user'],
                'createPickTicketAppJSON'               => $levels['user'],
                'clearWavePickAppJSON'                  => $levels['user'],
                'getWavePickDataAppJSON'                => $levels['user'],
                'getWavePickIDAppJSON'                  => $levels['user'],
                'getNewLabelAppJSON'                    => $levels['user'],
                'submitScanContainerAppJSON'            => $levels['user'],
                'automatedScanners'                     => $levels['user'],
                'batchScanners'                         => $levels['user'],
                'listContainers'                        => $levels['user'],
                'listFailsOnlineOrders'                 => $levels['user'],
                'incorrectOnlineOrders'                 => $levels['user'],
                'listUpdateFailsOnlineOrders'           => $levels['user'],
                'searchWorkOrders'                      => $levels['user'],
                'barcodeInventory'                      => $levels['user'],
                'searchVendors'                         => $levels['user'],
                'shippingNsi'                           => $levels['user'],
                'searchStyleLocationsScanners'          => $levels['user'],
                'styleLocationsScanners'                => $levels['user'],
                'inventoryTransferScanners'             => $levels['user'],
                'searchNoMezzanineScanners'             => $levels['user'],
                'noMezzanineScanners'                   => $levels['user'],
                'searchStyleUOMsScanners'               => $levels['user'],
                'styleUOMsScanners'                     => $levels['user'],
                'cartonLabelsTransfers'                 => $levels['user'],
                'shippedInventory'                      => $levels['user'],

                'displayPackingSlip'                    => $levels['user'],
                'displayPackingSlipGenius'              => $levels['user'],
                'printPrintPackingSlip'                 => $levels['user'],
                'displayPackingSlipPrathab'             => $levels['user'],
                'printPackingSlipPrathab'               => $levels['user'],
                'wavePicksOnlineOrders'                 => $levels['user'],
                'openOnlineOrdersReportOnlineOrders'    => $levels['user'],
                'displayWavePicks'                      => $levels['user'],
                'createWavePicks'                       => $levels['user'],

                'infoTallySheet'                        => $levels['user'],
                'printMasterLabels'                     => $levels['user'],
                'listMasterLabels'                      => $levels['user'],
                'printLabelsInventory'                  => $levels['user'],
                'printUccLabelsInventory'               => $levels['user'],
                'unsplitCartonsInventory'               => $levels['user'],
                'printSplitLabelsInventory'             => $levels['user'],
                'printUnSplitLabelsInventory'           => $levels['user'],
                'listSplitCartonsInventory'             => $levels['user'],
                'createTicketWavePicks'                 => $levels['user'],
                'createOrderPickTicketAppJSON'          => $levels['user'],
                'receivingToStockAppJSON'               => $levels['user'],
                'getPrintUccLabelsFileAppJSON'          => $levels['user'],
                'changOrdersBatchAppJSON'               => $levels['user'],
                'splitOrderCartonsAppJSON'              => $levels['user'],
                'getUPCDescriptionAppJSON'              => $levels['user'],
                'releaseCanceledOrderAppJSON'           => $levels['user'],
                'checkExportTableAppJSON'               => $levels['user'],
                'editLocationBatchAppJSON'              => $levels['user'],
                'displayLading'                         => $levels['user'],
                'searchUpcs'                            => $levels['user'],
                'getAutocompleteUpcAppJSON'             => $levels['user'],
                'getAutocompleteSkuAppJSON'             => $levels['user'],
                'printPageOrders'                       => $levels['user'],
                'printPageInvoices'                     => $levels['user'],
                'printStatementInvoices'                => $levels['user'],
                'displayContainers'                     => $levels['user'],
                'summaryCartonsInventory'               => $levels['user'],
                'summaryReportInventory'                => $levels['user'],
                'shippingInfoOrders'                    => $levels['user'],
                'styleLocationsInventory'               => $levels['user'],
                'addClientNotesAppJSON'                 => $levels['user'],
                'addOrderClientNotesAppJSON'            => $levels['user'],
                'receivingReportInventory'              => $levels['user'],
                'searchLocationsUtilizationLocations'   => $levels['user'],
                
                // Pages that need to be redone
                'scanSeldatContainers'                  => $levels['user'],
                'importSeldatContainers'                => $levels['user'],
                'checkImportSeldatUPCAppJSON'           => $levels['user'],
                'editSeldatContainers'                  => $levels['user'],
                'updateSeldatContainers'                => $levels['user'],
                'adminInvSeldatContainers'              => $levels['user'],
                'updateAdminInvSeldatContainers'        => $levels['user'],
                'generateReprintSeldatContainers'       => $levels['user'],
                'barcodeSeldatContainers'               => $levels['user'],
                'exportToCSVSeldatContainers'           => $levels['user'],
                'reprintBarcodeSeldatContainers'        => $levels['user'],

                'orderCheckInScanners'                  => $levels['user'],
                'orderCheckOutScanners'                 => $levels['user'],

                'orderEntryScanners'                    => $levels['user'],
                'orderProcessCheckOutScanners'          => $levels['user'],
                'workOrderCheckInScanners'              => $levels['user'],
                'workOrderCheckOutScanners'             => $levels['user'],
                'shippedScanners'                       => $levels['user'],
                'orderHoldScanners'                     => $levels['user'],

                'addOrEditOrders'                       => $levels['user'],
                'submitAddOrEditOrdersAppJSON'          => $levels['user'],
                'editOrders'                            => $levels['user'],
                'getClientStatusOrders'                 => $levels['user'],
                'orderStatusCountOrders'                => $levels['user'],

                'clientsCosts'                          => $levels['user'],

                'addModelAppJSON'                       => $levels['user'],
                'addLabelsWorkOrders'                   => $levels['user'],
                'searchInvoices'                        => $levels['user'],
                'searchContainers'                      => $levels['user'],

                'scanWorkOrders'                        => $levels['user'],
                'verifyWorkOrders'                      => $levels['user'],

                'displayDashboards'                     => $levels['user'],
                'searchLocations'                       => $levels['user'],
                'searchInventory'                       => $levels['user'],
                'migrationImports'                      => $levels['user'],
                'splitterInventory'                     => $levels['user'],
                'searchOrders'                          => $levels['user'],
                'updateStyleRowsAppJSON'                => $levels['user'],
                'addNsi'                                => $levels['user'],
                'listNsi'                               => $levels['user'],
                'confirmMezzanineTransfersScanners'     => $levels['user'],

                'listOrders'                            => $levels['user'],
                'importBatch'                           => $levels['user'],
                'failedImport'                          => $levels['user'],
                'exportEdi'                             => $levels['user'],
                'displayEdi'                            => $levels['user'],
                'downloadEdi'                           => $levels['user'],
                'changePasswordLogin'                   => $levels['user'],
                'createOrderPickTicketOrders'           => $levels['user'],
                'getStartDateStorageAppJSON'            => $levels['user'],
                'checkMezzanineStorageAppJSON'          => $levels['user'],

                'selectDashboards'                      => $levels['user'],
                'smartTVDashboards'                     => $levels['user'],
                'checkMezzanineLocationAppJSON'         => $levels['user'],
                'unsplitCartonsAppJSON'                 => $levels['user'],
                'reprintLicensePlateScanners'           => $levels['user'],
                'scanLicensePlateScanners'              => $levels['user'],
                'getCartonsByPlateInventory'            => $levels['user'],
                'getCartonsEditUomByPlatesInventory'    => $levels['user'],
                'updateUomCartonByPlateAppJSON'               => $levels['user'],

                'createReceiving'                       => $levels['user'],
                'displayReceiving'                      => $levels['user'],
                'updateReceiving'                       => $levels['user'],
                'getReceivingNumberAppJSON'             => $levels['user'],
                'createReceivingAppJSON'                => $levels['user'],
                'deleteReceivingAppJSON'                => $levels['user'],
                'checkRCLogContainerAppJSON'            => $levels['user'],
                'updateReceivingStatusAppJSON'          => $levels['user'],
                'confirmUpdateReceivingStatusAppJSON'   => $levels['user'],
                'downloadImportTemplateOrders'          => $levels['user'],
                'downloadTemplateTruckOrderWaves'       => $levels['user'],
                'importTruckOrderWaves'                 => $levels['user'],
                'emptyTruckOrderAppJSON'                => $levels['user'],
                'listAddBillOfLadings'                  => $levels['user'],
                'displayBillOfLadings'                  => $levels['user'],
                'addShipmentBillOfLadings'              => $levels['user'],
                'getAutocompleteOrderNumberAppJSON'     => $levels['user'],
                'getOrderInfoAppJSON'                   => $levels['user'],
                'getShipFromInfoAppJSON'                => $levels['user'],
                'searchBillOfLadings'                   => $levels['user'],
                'shippingReportsOrders'                 => $levels['user'],
                'pickingCheckOutOrders'                 => $levels['user'],
                'printProcessedLabelsInventory'         => $levels['user'],

                'updateCustomerContactAppJSON'          => $levels['user'],
                'insertCustomerContactAppJSON'          => $levels['user'],

                'updateInvoicePaymentAppJSON'           => $levels['user'],
                'cancelInvoiceAppJSON'                  => $levels['user'],
                'getClientLaborAppJSON'                 => $levels['user'],
                'submitWorkOrderAppJSON'                => $levels['user'],
                'getOrderDataByWorkOrderNumberAppJSON'  => $levels['user'],

                'workOrderCheckInVerifyAppJSON'         => $levels['user'],
                'workOrderCheckOutVerifyAppJSON'        => $levels['user'],

                // cycle count feature
                'createCycleCount'                      => $levels['user'],
                'viewCycleCount'                        => $levels['user'],
                'auditCycleCount'                       => $levels['user'],
                'getCustomerByWarehouseIDAppJSON'       => $levels['user'],
                'getCustomerNameByWarehouseIDAppJSON'   => $levels['user'],
                'printCyclePDFCycleCount'               => $levels['user'],
                'addCustomRowAppJSON'                   => $levels['user'],
                'saveCycleAppJSON'                      => $levels['user'],
                'loadUPCInfoFromAjaxAppJSON'            => $levels['user'],
                'getSKUByClientIDAppJSON'               => $levels['user'],
                'autocompleteLocationsWarehouseAppJSON' => $levels['user'],
                'checkLocationOnWarehouseAppJSON'       => $levels['user'],
                'getSKUByWarehouseIDAppJSON'            => $levels['user'],
                'checkLocationCycleCountAppJSON'        => $levels['user'],
                'autoSaveContainerAppJSON'              => $levels['user'],
                'processSearchSKUAppJSON'               => $levels['user'],
                'searchSKUAutoCompleteAppJSON'          => $levels['user'],
                'reportOpenOrders'                      => $levels['user'],
                'styleHistoryInventory'                 => $levels['user'],
                'componentsInventory'                   => $levels['user'],
                'checkOnlineOrdersShipPasswordAppJSON'  => $levels['user'],
                'checkReceivingAppJSON'                 => $levels['user'],
                'processRequestAppJSON'                 => $levels['user'],

                'searchWarehouseTransfers'              => $levels['user'],
                'searchWarehouseTransferPallets'        => $levels['user'],
                'warehouseInboundTransferScanners'      => $levels['user'],
                'warehouseOutboundTransferScanners'     => $levels['user'],
                'warehouseTransferConsolidationScanners'=> $levels['user'],

                'reportIssues'                          => $levels['user'],

                // Pages you don't need to be a user to view
                'logout'                                => $levels['none'],
                'userLogin'                             => $levels['none'],
                'dialogLoginJson'                       => $levels['none'],
                'importOrdersEdi'                       => $levels['none'],
                'sessionRequestJson'                    => $levels['none'],
                'updateFeatureShowStatusAppJSON'        => $levels['none'],
                'ajaxErrorSubmitJson'                   => $levels['none'],
                'apiAppJSON'                            => $levels['none'],
                'reqJWTAppJSON'                         => $levels['none'],
            ],

            // Custom WMS Access for Clients
            'clientAccess' => [
                'componentsLogs'            => TRUE,
                'availableInventory'        => TRUE,
                'displayDashboards'         => TRUE,
                'datatablesJson'            => TRUE,
                'menuMain'                  => TRUE,
                'summaryReportInventory'    => TRUE,
                'displayContainers'         => TRUE,
                'styleLocationsInventory'   => TRUE,
                'summaryCartonsInventory'   => TRUE,
                'componentsInventory'       => TRUE,
                'searchContainers'          => TRUE,
                'shippingReportsOrders'     => TRUE,
                'searchReceivedContainers'  => TRUE,
                'addClientNotesAppJSON'     => TRUE,
                'searchOrders'              => TRUE,
                'addOrderClientNotesAppJSON' => TRUE,
                'filterSearcherJson'         => TRUE,
                'styleHistoryInventory'      => TRUE,
                'changePasswordLogin'        => TRUE,
            ],
        ];

        return $index ? getDefault($pages['access'][$index]) : $pages;
    }

    /*
    ****************************************************************************
    */

    static function check($params)
    {
        $pageRequest = \models\config::formRequest($params);
        return self::get($pageRequest);
    }
}
